name: run main.py

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '40 11,16 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '3.12'

      - name: Sync environment with uv
        run: uv sync

      - name: Execute py script
        env:
          LOCATION: ${{ secrets.LOCATION }}
          NUMBER: ${{ secrets.NUMBER }}
          PASSPORT_NUMBER: ${{ secrets.PASSPORT_NUMBER }}
          SURNAME: ${{ secrets.SURNAME }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SMTP: ${{ secrets.SMTP }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: uv run trigger.py

      - name: Upload status artifact
        uses: actions/upload-artifact@v4
        with:
          name: status-artifact
          path: status_record.json
